spring:
  redis:
    host: 10.140.113.197
    port: 6379
    database: 4
  output:
    ansi:
      enabled: DETECT
logging:
  level:
    org:
      kurento:
        nodeValue: INFO
        tutorial: INFO
      springframework: WARN
      apache: WARN
    root: INFO
banner:
  location: classpath:banner.txt
server:
  port: '8443'
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
      exposure:
        include: health