spring:
  redis:
    host: "localhost"
    port: 6379
  output:
    ansi:
      enabled: DETECT
logging:
  level:
    org:
      kurento:
        nodeValue: INFO
        tutorial: INFO
      springframework: WARN
      apache: WARN
    root: INFO
banner:
  location: classpath:banner.txt
server:
  port: '8443'