server:
  port: 8080

spring:
  # kurento config
  kurento:
    host: ws://10.140.113.213:8888/kurento # aws
  redis:
    host: localhost
    port: 6379
    database: 0

upload:
  server:
    url: http://localhost:9090/media/upload