server:
  servlet:
    context-path: /signal

spring:
  application:
    name: signal
  profiles:
    default: dev
  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      kurento:
        nodeValue: INFO
        tutorial: INFO
      springframework: WARN
      apache: WARN
    root: INFO

# health check management
management:
  endpoints:
    web:
      base-path: /healthcheck
      path-mapping:
        health: _check
